{
  "status": "error",
  "message": "This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pg8000.dbapi.ProgrammingError) {'S': 'ERROR', 'V': 'ERROR', 'C': '42703', 'M': 'column \"is_healthy\" of relation \"endpoint_health\" does not exist', 'P': '62', 'F': 'parse_target.c', 'L': '1070', 'R': 'checkInsertTargets'}\n[SQL: INSERT INTO endpoint_health (discovered_endpoint_id, status, is_healthy, response_time, checked_at, status_code, error_message, failure_reason) VALUES (%s::INTEGER, %s::VARCHAR, %s::BOOLEAN, %s::FLOAT, %s::TIMESTAMP WITHOUT TIME ZONE, %s::INTEGER, %s::VARCHAR, %s::VARCHAR) RETURNING endpoint_health.endpoint_health_id]\n[parameters: (1, 'error', False, None, datetime.datetime(2025, 6, 17, 14, 24, 52, 468878), None, None, \"'ClientResponse' object has no attribute 'elapsed'\")]\n(Background on this error at: https://sqlalche.me/e/20/f405) (Background on this error at: https://sqlalche.me/e/20/7s2a)"
}